# For more info see https://yarnpkg.com/advanced/telemetry
enableTelemetry: false

# Experimental but we need this for the migration (we’ll switch it later)
nodeLinker: "node-modules"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

# https://yarnpkg.com/configuration/yarnrc#preferInteractive
preferInteractive: true

yarnPath: .yarn/releases/yarn-2.4.1.cjs
